FROM node:14-buster AS builder

COPY package-lock.json package.json /build/

WORKDIR /build

RUN npm ci

COPY . /build

RUN npm run build:prod

FROM nginx:1.19-alpine

COPY --from=builder /build/dist /usr/share/nginx/html/

# GCP Cloud run requires PORT environment variable which dictates the listening port.
# Use sed to alter the listening port in runtime.
CMD set -e; sed -i "s/listen       80/listen $PORT/" /etc/nginx/conf.d/default.conf && \
  nginx -g "daemon off;"
