version: '3.7'
services:
  client:
    image: gcr.io/turbothrift/turbothrift_client_dev
    build: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:8080
    networks:
      - turbothriftnet
  server:
    image: gcr.io/turbothrift/turbothrift_server_dev
    build: server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
    environment:
      - GOOGLE_CLIENT_ID
      - PORT=4000
    networks:
      - turbothriftnet
    depends_on:
      - database
  database:
    networks:
      - turbothriftnet
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf

networks:
  turbothriftnet:
    name: turbothriftnet
