version: '3'
services:
  client:
    build: client
    volumes:
      - ./client/src:/app/src
    ports:
      - 8080:8080
  server:
    build: server
    volumes:
      - ./server/src:/app/src
    ports:
      - 4000:4000
