version: '3'
services:
  client:
    build: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 8080:8080
  server:
    build: server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf
