version: '3.7'
services:
  scrape:
    image: ghcr.io/je-l/turbothrift_scrape
    environment:
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - EMAIL_SENDER_NAME
      - EMAIL_SENDER_ADDRESS
    build: scrape
    volumes:
      - ./scrape:/scrape
      - /scrape/node_modules
    restart: "no"
    networks:
      - turbothriftnet

networks:
  turbothriftnet:
    external: true
